spring:
    application:
        name: sbcboardweather
    datasource:
        url: jdbc:mysql://localhost:3306/java_basic?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: akdptmzbdpf10299!!


mybatis:
    mapper-locations: classpath:mappers/*.xml

server:
    port: 8081

weather:
    api:
        url: "http://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst"
        key: "GQOL4FopR36Ra82FGjhZqMzR4kYKJT%2FuSgo7wGX8iclyQs3kx406tY%2Bt5oLtPq9QkWRyBV4W6oXMk2eQ%2FWp1BA%3D%3D"
