apiVersion: v1
kind: Service
metadata:
  name: web-front-admin-service
spec:
  selector:
    app: web-front-admin-service
  ports:
    - protocol: TCP
      port: 8886  # 외부 접근 포트
      targetPort: 8886  # 실제 컨테이너가 리스닝하는 포트
  type: ClusterIP